# Copyright (c) Ely Deckers.
#
# This source code is licensed under the MPL-2.0 license found in the
# LICENSE file in the root directory of this source tree.

version: "2.3"

services:
  huemon:
    image: edeckers/huemon:0.7.1
    volumes:
    - huemon-config:/etc/huemon
    - huemon-opt:/opt/huemon
    - huemon-log:/var/log/huemon
    command: ["agent", "start"]
    ports:
      - 127.0.0.1:8000:80
volumes:
  huemon-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/config
  huemon-log:
  huemon-opt:
